config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("dingoapp.urls")),
    path('blog/', include("blogapp.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


# Create your models here.

class User(AbstractUser):
    avatar = models.ImageField(upload_to='users/avatar/')

    def __str__(self):
        return self.username


class Category(models.Model):
    category_name = models.CharField(max_length=150)

    def __str__(self):
        return self.category_name


class Coments(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    message = models.TextField()
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True)
    best_comment = models.BooleanField(default=False)

    def __str__(self):
        return self.message[:10]


class Post(models.Model):
    title = models.CharField(max_length=220)
    content = models.TextField()
    category = models.ManyToManyField(Category)
    image = models.ImageField(upload_to='blog/')
    like = models.ManyToManyField(User, related_name='like', null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def num_of_likes(self):
        return self.like.count()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('sin_blog', kwargs={'pk': str(self.pk)})

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <h2>About Us</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!-- about part start-->
    <section class="about_part about_bg">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-sm-4 col-lg-5 offset-lg-1">
                    <div class="about_img">
                        <img src="{% static 'img/about.png' %}" alt="">
                    </div>
                </div>
                <div class="col-sm-8 col-lg-4">
                    <div class="about_text">
                        <h5>Our History</h5>
                        <h2>Where The Food’s As Good
                            As The Root Beer.</h2>
                        <h4>Satisfying people hunger for simple pleasures</h4>
                        <p>May over was. Be signs two. Spirit. Brought said dry own firmament lesser best sixth deep
                            abundantly bearing, him, gathering you
                            blessed bearing he our position best ticket in month hole deep </p>
                        <a href="#" class="btn_3">Read More <img src="{% static 'img/icon/left_2.svg' %}" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- about part end-->
    <!--::review_part start::-->
    <section class="review_part gray_bg section_padding">
        <div class="container">
            <div class="row">
                <div class="col-xl-5">
                    <div class="section_tittle">
                        <p>Testimonials</p>
                        <h2>Customers Feedback</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-11">
                   <div class="client_review_part owl-carousel">

                        {% for best in best %}
                        <div class="client_review_single media">
                            <div class="client_img align-self-center">
                                <img src="{{ best.user.avatar.url }}" alt="">
                            </div>
                            <div class="client_review_text media-body">
                                <p>{{ best.message }}</p>
                                <h4>{{ best.user.username }}, <span>Executive of fedex</span></h4>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--::review_part end::-->
    <!--::chefs_part start::-->
    <section class="chefs_part blog_item_section section_padding" id="myTab" role="tablist">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-5">
                    <div class="section_tittle">
                        <p>Team Member</p>
                        <h2>Our Experience Chefs</h2>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="nav nav-tabs food_menu_nav" style="justify-content: space-between">

                        {% for level in level %}
                        {% if level.ch_level == cat %}
                            <a class="active" href="?cat={{ level.ch_level }}#myTab">{{ level.ch_level }} <img src="{% static 'img/icon/play.svg' %}"
                                alt="play"></a>
                        {% else %}
                            <a href="?cat={{ level.ch_level }}#myTab">{{ level.ch_level }}</a>
                            {% endif %}
                        {% endfor %}

                    </div>
                </div>
                <div class="col-lg-12">
                <div class="tab-pane fade show active single-member" id="Special" role="tabpanel" aria-labelledby="Special-tab">
                            <div class="row">

                                <div class="col-sm-6 col-lg-6">
                                    {% for food in foods3 %}
                                    <div class="single_food_item media">
                                        <img src="{{ food.picture.url }}" class="mr-3" alt="..." height="109.5"; width="271.3">
                                        <div class="media-body align-self-center">
                                            <h3>{{ food.title }}</h3>
                                            <p>{{ food.about }}</p>
                                            <h5>${{ food.price }}</h5>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>

                                <div class="col-sm-6 col-lg-6">
                                    {% for food in foods6 %}
                                    <div class="single_food_item media">
                                        <img src="{{ food.picture.url }}" class="mr-3" alt="..." height="109.5"; width="271.3">
                                        <div class="media-body align-self-center">
                                            <h3>{{ food.title }}</h3>
                                            <p>{{ food.about }}</p>
                                            <h5>${{ food.price }}</h5>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>

                            </div>
                        </div>
                </div>
            </div>
            <div class="row">

                {% for chef in chefs %}
                <div class="col-sm-6 col-lg-4">
                    <div class="single_blog_item">
                        <div class="single_blog_img">
                            <img src="{{ chef.picture.url }}" alt="" height="360"; width="330"; style="border-radius: 15px 15px 0 0"  >
                        </div>
                        <div class="single_blog_text text-center">
                            <h3>{{ chef.full_name }}</h3>
                            <p>{{ chef.level }}</p>
                            <div class="social_icon">
                                <a href="{{ chef.fasebook }}"> <i class="ti-facebook"></i> </a>
                                <a href="{{ chef.x_tvit }}"> <i class="ti-twitter-alt"></i> </a>
                                <a href="{{ chef.instagram }}"> <i class="ti-instagram"></i> </a>
                                <a href="{{ chef.skype }}"> <i class="ti-skype"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
    <!--::chefs_part end::-->

{% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <h2>Our Blog</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->


    <!--================Blog Area =================-->
    <section class="blog_area section_padding" id="mytab" role="tablist">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">

                        {% for post in posts %}
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{{ post.image.url }}" alt="">
                                <a href="#" class="blog_item_date">
                                    <h3>{{ post.created | date:'d' }}</h3>
                                    <p>{{ post.created | date:'M' }}</p>
                                </a>
                            </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{{ post.get_absolute_url }}">
                                    <h2>{{ post.title }}</h2>
                                </a>
                                <p>{{ post.content | truncatewords:10 }}</p>
                                <ul class="blog-info-link">
                                    {% for cat in post.category.all %}
                                    <li><a href="#"><i class="far fa-user"></i>{{ cat }}</a></li>
                                     {% endfor %}
                                    <li><a href="#"><i class="far fa-comments"></i>{{post.coments_set.count}} Comments</a></li>
                                </ul>
                            </div>
                        </article>
                        {% endfor %}

                        <nav class="blog-pagination justify-content-center d-flex">
                            <ul class="pagination">

                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a href="?page={{ page_obj.previous_page_number }}#mytab" class="page-link" aria-label="Previous">
                                        <i class="ti-angle-left"></i>
                                    </a>

                                </li>
                                 <li class="page-item ">
                                    <a href="?page={{ page_obj.previous_page_number }}#mytab" class="page-link">{{ page_obj.previous_page_number }}</a>
                                </li>

                            {% endif %}


                                <li class="page-item active">
                                    <a href="?page={{ page_obj.number }}#mytab" class="page-link">{{ page_obj.number }}</a>
                                </li>


                                {% if page_obj.has_next %}

                                     <li class="page-item ">
                                    <a href="?page={{ page_obj.next_page_number }}#mytab" class="page-link">{{ page_obj.next_page_number }}</a>
                                </li>

                                <li class="page-item">
                                    <a href="?page={{ page_obj.next_page_number }}#mytab" class="page-link" aria-label="Next">
                                        <i class="ti-angle-right"></i>
                                    </a>
                                </li>
                                {% endif %}

                            </ul>
                        </nav>
                    </div>
                </div>
                {% include 'side.html' %}
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->

{% endblock %}

templates/side.html
<div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget search_widget">
                            <form action="#">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder='Search Keyword'
                                            onfocus="this.placeholder = ''"
                                            onblur="this.placeholder = 'Search Keyword'">
                                        <div class="input-group-append">
                                            <button class="btn" type="button"><i class="ti-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_4"
                                    type="submit">Search</button>
                            </form>
                        </aside>

                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Category</h4>
                            <ul class="list cat-list">
                              {% for cat in categories %}
                                <li>
                                    <a href="" class="d-flex">
                                        <p>{{ cat.category_name }}</p>
                                        <p>({{ cat.post_set.count }})</p>
                                    </a>
                                </li>
                              {% endfor %}
                            </ul>
                        </aside>

                        <aside class="single_sidebar_widget popular_post_widget">
                            <h3 class="widget_title">Recent Post</h3>

                            {% for post in recent %}
                            <div class="media post_item">
                                <img src="{{ post.image.url }}" alt="post" style="width: 80px; height: 80px">
                                <div class="media-body">
                                    <a href="{{ post.get_absolute_url }}">
                                        <h3>{{ post.title }}</h3>
                                    </a>
                                    <p>{{ post.created }}</p>
                                </div>
                            </div>
                           {% endfor %}

                        </aside>
                        <aside class="single_sidebar_widget tag_cloud_widget">
                            <h4 class="widget_title">Tag Clouds</h4>
                            <ul class="list">
                                <li>
                                    <a href="#">project</a>
                                </li>
                                <li>
                                    <a href="#">love</a>
                                </li>
                                <li>
                                    <a href="#">technology</a>
                                </li>
                                <li>
                                    <a href="#">travel</a>
                                </li>
                                <li>
                                    <a href="#">restaurant</a>
                                </li>
                                <li>
                                    <a href="#">life style</a>
                                </li>
                                <li>
                                    <a href="#">design</a>
                                </li>
                                <li>
                                    <a href="#">illustration</a>
                                </li>
                            </ul>
                        </aside>


                        <aside class="single_sidebar_widget instagram_feeds">
                            <h4 class="widget_title">Instagram Feeds</h4>
                            <ul class="instagram_row flex-wrap">

                                {% for p in posts %}
                                <li>
                                    <a href="{{ p.get_absolute_url }}">
                                        <img class="img-fluid" src="{{ p.image.url }}" alt="">
                                    </a>
                                </li>
                                {% endfor %}

                            </ul>
                        </aside>


                        <aside class="single_sidebar_widget newsletter_widget">
                            <h4 class="widget_title">Newsletter</h4>

                            <form action="#">
                                <div class="form-group">
                                    <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_4"
                                    type="submit">Subscribe</button>
                            </form>
                        </aside>
                    </div>
                </div>

templates/single-blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

   <!-- breadcrumb start-->
   <section class="breadcrumb breadcrumb_bg">
      <div class="container">
         <div class="row">
            <div class="col-lg-12">
               <div class="breadcrumb_iner text-center">
                  <div class="breadcrumb_iner_item">
                     <h2>Single Blog</h2>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!-- breadcrumb start-->
   <!--================Blog Area =================-->
   <section class="blog_area single-post-area section_padding">
      <div class="container">
         <div class="row">
            <div class="col-lg-8 posts-list">
               <div class="single-post">
                  <div class="feature-img">
                     <img class="img-fluid" src="{{ post.image.url }}" alt="">
                  </div>
                  <div class="blog_details">
                     <h2 class="d-flex align-items-center">
                         {{ post.title }}
                    <form class="ml-4" method="post" >
                        {% csrf_token %}

                        {% if post_is_liked %}
                             <input class="genric-btn success-border circle active" type="submit" value="💔">
                        {% else %}
                            <input class="genric-btn success-border circle active" type="submit" value="❤️">
                        {% endif %}

                    </form>
                     </h2>
                     <ul class="blog-info-link mt-3 mb-4">
                         {% for fo in post.category.all %}
                        <li><a href="#"><i class="far fa-user"></i>{{ fo.category_name }}</a></li>
                         {% endfor %}
                        <li><a href="#"><i class="far fa-comments"></i> {{ post.coments_set.count }} Comments</a></li>
                     </ul>
                       <p>{{ post.content}}</p>
                  </div>
               </div>
               <div class="navigation-top">
                  <div class="d-sm-flex justify-content-between text-center">
                     <p class="like-info"><span class="align-middle"><i class="far fa-heart"></i></span> {{ post.like.count }}
                        people like this</p>
                     <div class="col-sm-4 text-center my-2 my-sm-0">
                        <!-- <p class="comment-count"><span class="align-middle"><i class="far fa-comment"></i></span> 06 Comments</p> -->
                     </div>
                     <ul class="social-icons">
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fab fa-behance"></i></a></li>
                     </ul>
                  </div>
                  <div class="navigation-area">
                     <div class="row">
                        <div
                           class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                           <div class="thumb">
                              <a href="{{ previous.get_absolute_url }}">
                                 <img class="img-fluid" src="{{ previous.image.url }}" alt="" style="height: 150px; width: 150px">
                              </a>
                           </div>
                           <div class="arrow">
                              <a href="{{ previous.get_absolute_url }}">
                                 <span class="lnr text-white ti-arrow-left"></span>
                              </a>
                           </div>
                           <div class="detials">
                              <p>Prev Post</p>
                              <a href="{{ previous.get_absolute_url }}">
                                 <h4>{{ previous.title }}</h4>
                              </a>
                           </div>
                        </div>

                        <div
                           class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                           <div class="detials">
                              <p>Next Post</p>
                              <a href="{{ next.get_absolute_url }}">
                                 <h4>{{ next.title }}</h4>
                              </a>
                           </div>
                           <div class="arrow">
                              <a href="{{ next.get_absolute_url }}">
                                 <span class="lnr text-white ti-arrow-right"></span>
                              </a>
                           </div>
                           <div class="thumb">
                              <a href="{{ next.get_absolute_url }}">
                                 <img class="img-fluid" src="{{ next.image.url }}" alt="" style="height: 150px; width: 150px">
                              </a>
                           </div>
                        </div>

                     </div>
                  </div>
               </div>

                {% if best.user is not None %}
               <div class="blog-author">
                  <div class="media align-items-center">
                     <img src="{{ best.user.avatar.url }}" alt="">
                     <div class="media-body">
                        <a href="#">
                           <h4>{{ best.user.username }}</h4>
                        </a>
                        <p>{{ best.message }}</p>
                     </div>
                  </div>
               </div>
                {% endif %}

               <div class="comments-area">
                  <h4>{{ comment.count }} Comments</h4>

                   {% for coment in comment %}
                  <div class="comment-list">
                     <div class="single-comment justify-content-between d-flex">
                        <div class="user justify-content-between d-flex">
                           <div class="thumb">
                              <img src="{{ coment.user.avatar.url }}" alt="">
                           </div>
                           <div class="desc">
                              <p class="comment">
                                {{ coment.message }}
                              </p>
                              <div class="d-flex justify-content-between">
                                 <div class="d-flex align-items-center">
                                    <h5>
                                       <a href="#">{{ coment.user.username }}</a>
                                    </h5>
                                    <p class="date">{{ coment.created|date:'M d, Y   h:i' }} </p>
                                 </div>
                                 <div class="reply-btn">
                                    <a href="#" class="btn-reply text-uppercase">reply</a>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
                    {% endfor %}

               </div>
               <div class="comment-form">
                  <h4>Leave a Reply</h4>
                  <form class="form-contact comment_form" action="#" id="commentForm">
                     <div class="row">
                        <div class="col-12">
                           <div class="form-group">
                              <textarea class="form-control w-100" name="comment" id="comment" cols="30" rows="9"
                                 placeholder="Write Comment"></textarea>
                           </div>
                        </div>
                        <div class="col-sm-6">
                           <div class="form-group">
                              <input class="form-control" name="name" id="name" type="text" placeholder="Name">
                           </div>
                        </div>
                        <div class="col-sm-6">
                           <div class="form-group">
                              <input class="form-control" name="email" id="email" type="email" placeholder="Email">
                           </div>
                        </div>
                        <div class="col-12">
                           <div class="form-group">
                              <input class="form-control" name="website" id="website" type="text" placeholder="Website">
                           </div>
                        </div>
                     </div>
                     <div class="form-group">
                        <button type="submit" class="button button-contactForm">Send Message</button>
                     </div>
                  </form>
               </div>
            </div>
            {% include 'side.html' %}
         </div>
      </div>
   </section>
   <!--================Blog Area end =================-->

{% endblock %}